apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: production
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: louiskimlevu/nodejs-repo:nodejs-ed4b0eaa
        ports:
        - containerPort: 8080