apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: production
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
