---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: dev
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: louiskimlevu/nodejs-repo:nodejs-13ff15a8
        ports:
        - containerPort: 8080
